### ISSUE TITLE
Check access control checks for predicate, user-groups, and categories management

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1001]
Hi!

When i add a use group members and allow them the use of mod_admin they can change or remove predicates. You get the menu item structure but if you go to categories you get the login screen again. Think this is a bug.

~ Dorien

**Comment by mworrell** [comment]
The "predicates" are available if the user is allowed to create a predicate: ``{acl, insert, predicate}``
The predicates page itself only depends on access to controller_admin.

With the mod_admin_category there is something irregular: the menu item appears on ``{acl, insert, category}`` but the category sorter page depends on ``{acl, use, mod_admin_category}``.  So the user needs to be able to create a category _and_ have "use" rights on mod_admin_category.

Maybe we can make these checks a bit simpler so that both follow the same pattern.

**Comment by mworrell** [comment]
Fixed by #1514
