### ISSUE TITLE
mod_admin_identity: non sysadmin can't add user and logon as user

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1033]
It should be possible for usergroup  "Administrators" to add new users and test the acl's by logging in as a user. We don't want to give the client the admin password.

**Comment by DorienD** [comment]
Any ideas on when this could be improved?

**Comment by mworrell** [comment]
I propose to check on the permission `use:mod_admin_identity`

Though the *login as user* is quite a powerful options, so maybe we want to have that one more closed.

Any comments?

@arjan @ArthurClemens @mmzeeman

**Comment by ArthurClemens** [comment]
I guess that "log in as another user" should also be limited to `use:mod_admin_identity`, if that isn't the case already.

**Comment by mmzeeman** [comment]
We use it quite a lot. It is indeed very handy to check acl permission of users. Our admin logs in as admin. For now he uses the "admin" an extra permission would be nice indeed.

**Comment by mworrell** [comment]
Turns out that `m.acl.is_admin` checked on the permission `use.mod_admin_config`, whereas `z_acl:is_admin/1` only checked for the user 1 or a *sudo* context.

I made this equal by having `m.acl.is_admin` call `z_acl:is_admin(Context)` and have the `z_acl:is_admin` also check for the permission use.mod_admin_config.

Now everybody with the `use.mod_admin_config` permission can log on as another user.
