### ISSUE TITLE
Webmachine access logger should be faster

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1067]
The current webmachine logger is kind of slow. If we want to improve the performance of zotonic we should improve it.

It currently rotates log every hour. This means that the server can't run unattended because the log files can become very big on a busy server. A server with around 6 million hits per day generates about 1.4 gigabyte of logs.

A considerable amount of times is spent formatting each line, and is discarded most of the time.

This especially leads to problems when the dispatcher bottleneck is removed.

(Screenshot from etop of zotonic under stress with ets based dispatcher)

<img width="651" alt="screen shot 2015-10-22 at 12 06 44" src="https://cloud.githubusercontent.com/assets/1024972/10701873/5519d5b2-79c6-11e5-89f3-f2b6e8040577.png">

**Comment by CyBeRoni** [comment]
I like what HAProxy does. It uses syslog and either uses a socket for that or can log over the network using UDP. Using syslog you can then write it to a file (which is done outside zotonic) or you can feed it into logstash or some other centralised logging system. An added benefit is that it's fire-and-forget: if the syslog server is unavailable, this does not affect zotonic at all.

Another option is the varnish approach, which is to log to shared memory and have a separate program fetch the log data from shared memory and do log formatting and output independently. 

I have a slight preference for the haproxy approach, mostly because it is simper with fewer moving parts.

**Comment by mmzeeman** [comment]
LOL :-) the current hourly log is very bad indeed. But with a simple wc command you have hourly stats ;-)

**Comment by mmzeeman** [comment]
Master has a new log system via syslog(3) system call.

**Comment by ddeboer** [comment]
Can we close this issue now we’ve moved to Cowboy?

**Comment by mworrell** [comment]
Yes, closing as we will have new access logging for cowmachine
