### ISSUE TITLE
Cherry-pick dispatch compile optimizations from master to 0.13.x

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1121]

**Comment by mmzeeman** [comment]
This needs some thorough testing. Especially if we exclude the other request optimisations. The old dispatcher served as a throttler for everything behind it. Removing this throttle could cause problems for heavily visited sites.

**Comment by mworrell** [comment]
Some optimizations are already cherry-picked.
The new dispatcher can't go full throttle anyway due to the needed list to binary (and back) conversions.

The new dispatcher will fix an issue where we the gen_server based dispatcher is starved and starts to timeout on cpu-constrained or swapping servers.

**Comment by mmzeeman** [comment]
But requests are more parallel with the new dispatcher. During testing I saw some access log issues, but that was with 10k req/s

**Comment by mworrell** [comment]
I merged it and it looks fine. Did two backwards compatibility changes to translate from and to lists.
