### ISSUE TITLE
Refactor z_ids module

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1150]
This module generates list based random identifiers, numbers and ids used throughout zotonic modules.

The current implementation is a gen_server, which can become a bottleneck when a lot of ids are requested. With the upcoming binarification of zotonic we should generate id's and identifiers as binaries, and use ```crypto:randbytes/1``` so the gen_server can be removed. 

*Note: This is a breaking change*

**Comment by ddeboer** [comment]
@willemdj Is this a good one for you to work one? Nice introduction to Zotonic. :wink:

**Comment by willemdj** [comment]
I am still new to this, so I hope it is okay if I ask a couple of questions.

__Getting rid of the gen_server__
Under normal operational circumstances the functions in the module are all stateless, so they don't need a gen_server. 

Only when the server is started with the `fixed_seed` option or after execution of `z_ids:fix_seed()` the state becomes important: it changes the behavior of some of the functions, and some of those are no longer stateless.

I believe that it would be possible to change this approach in such a way that the API functions are executed without the gen_server under normal circumstances. This could be done by loading a different version of the module under test circumstances. Perhaps using a compiler directive, or using something like meck. Alternatively it could be based on m_config or aplication:get_env()

Questions: 
- is it important to keep the `fix_seed` functionality,
- if so, must the interface to use activate that functionality remain exactly as it is today, or would it be acceptable to achieve the same result in another way, for example by re-compiling and reloading the module.

__Efficieny and move to binary__
The exact requirements for each of the functions in the module are not clear to me. In order to rewrite the functions to return a binary value, it would be good to understand exactly which aspects of the current implementation are really required, and which are the results of implementation choices.

- Is it the expectation that `id` and `identifier` are unique? (in what context 
  or with what periodicity?) 
- Must they be random? Or is the random function used as a way to achieve uniqueness?
- Must the identifiers be exactly of the specified length, or is the length used as a way to guarantee a certain level of uniqueness?

(I would assume that the main requirement for session ids and ids in HTML etc is that they are unique, rather than random?)

I can imagine that it may be efficient  to use `erlang:unique_integer().` Whether that is acceptable or not depends on the exact requirements.

For example `integer_to_binary(erlang:unique_integer([positive]))` gives values that are unique (as long as the VM is not restarted) in a very efficient way, but they are not random, they contain only numbers and they are not of a fixed length (but they could be made to be, with certain limitations).

**Comment by ddeboer** [comment]
Good questions!

Did you look into `crypto:rand_bytes` (mentioned by @mmzeeman above) and `crypto:strong_rand_bytes`?

@mworrell @mmzeeman Just to make sure: is the intention indeed to get rid of gen_server for generating the ids, or are we looking for a more efficient way to do so?

**Comment by arjan** [comment]
We want to remove the `gen_server` altogether to remove the bottleneck that it can create.
I would also vote for removing the "fix_seed" functionality; a quick grep shows that it is only used on [one place](https://github.com/zotonic/zotonic/blob/master/modules%2Fmod_base%2Ftests%2Fmod_admin_tests.erl), in a test, and the assertions are commented out anyway.

**Comment by mmzeeman** [comment]
Session ids should be unpredictable too. This is needed because you don't want an attacker to be able to guess them. The OWASP site has good documentation on how to generate them. You basically need a good rng to do this.

The reason why the gen_server should go is that it can become a bottleneck. It is just one server which has to do things for numerous other processes. 

Verstuurd vanaf mijn iPhone

**Comment by willemdj** [comment]
I'll rewrite the module without the gen_server and without the "fix_seed_ functionality then, that will be easy enough.

I'll also change the responses to be binary, and I'll make the required changes to the modules that call the functions.  

While doing that I'll try to understand what the IDs are used for, and perhaps come up with some changes in the way the IDs are generated or with one or two additional functions if I think there are considerable performance gains to be made.

**Comment by arjan** [comment]
Sounds great!

**Comment by mworrell** [comment]
I am completely for binary results. We are moving the master (1.0) to use binaries instead of strings anyway.

And good analysis of this module 👍

**Comment by mmzeeman** [comment]
This morning I looked at https://bugs.ruby-lang.org/issues/9569 and checked what erlang was doing.

A quick inspection showed that `crypto:rand_bytes/1` is not good enough for generating session ids, but for all the other things it should be ok. 

The problem is that `rand_bytes` uses openssl's `RAND_pseudo_bytes` (which is deprecated). From their documentation: Pseudo-random byte sequences generated by `RAND_pseudo_bytes()` will be unique if they are of sufficient length, but are not necessarily unpredictable.

**Comment by willemdj** [comment]
Ok, good to know.

It took me some time to get going, since I normally work on a windows PC.
But I have zotonic running now, and started to make some changes.

**Comment by ddeboer** [comment]
Fixed in #1270.
