### ISSUE TITLE
error in translation ru.po mod_authentication

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1197]
msgid "Sign in"
msgid #-#-#-#-#  ru.po (zotonic-0.10-dev)  #-#-#-#-#
Войти
#-#-#-#-#  ru.po (zotonic-0.10-dev)  #-#-#-#-#
Вход
want to replace
**Вход**

**Comment by mworrell** [comment]
So "Sign in" must be "Вход" ?

**Comment by heiheshang** [comment]
Ok

**Comment by heiheshang** [comment]
0.13.8 release again mistranslation

**Comment by ddeboer** [comment]
That is correct: [0.13.8](https://github.com/zotonic/zotonic/releases/tag/0.13.8) was a hotfix release to get rid of the leap year bug. As it was a hotfix, it contains only the bugfix and is otherwise identical to 0.13.7.

The fixed translations are in the next monthly tag (0.14.0), to be released tomorrow. :wink:
