### ISSUE TITLE
Become the first to implement letsencrypt by default

### ISSUE THREAD

**Issue by jult** [zotonic/zotonic#1218]
We're at that point now, where nginx is already working on a default https config with letsencrypt. Zotonic could be among the first web-serving systems offering TLS for each domain by default.

**Comment by mmzeeman** [comment]
We could sure use some PR. We probably need to have SNI support first if we want to do this. This is something I want to look at if I find some time the next couple of weeks.

**Comment by ddeboer** [comment]
See #364.

**Comment by mmzeeman** [comment]
We, sort of, need it for a site which has a couple of aliases.

**Comment by mmzeeman** [comment]
No time budget at work of course, but it looks like a doable weekend project. :-)

**Comment by arjan** [comment]
Note that letsencrypt certificates have a short expiration period (90 days iirc). So the implementation has to deal with that by automating the entire certification process (domain validation included).

**Comment by ddeboer** [comment]
That's exactly the idea, @arjan. :wink:

**Comment by arjan** [comment]
:-P

**Comment by CyBeRoni** [comment]
You wouldn't be the first though. By a [rather large margin…](http://caddyserver.com).

**Comment by ArthurClemens** [comment]
I have gone through the process twice now: once for the first certificate, today for the renewal.

This is my writeup, in case it is useful for creating a module.

## Installing Letsencrypt

Default install location (following the [documentation](http://letsencrypt.readthedocs.org)) is `/opt/letsencrypt`:

```
sudo git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
```

This setup requires root access. I have not yet tried yet installing it someplace else, for instance in a directory controlled by the Zotonic user. Letsencrypt writes to `/etc/`, so perhaps root access cannot be avoided.


## Creating new certificates

### Preparation: openssl.cnf

File `/etc/ssl/openssl.cnf` should contain [subjectAltName](http://wiki.cacert.org/FAQ/subjectAltName). At the end of `openssl.cnf`, add:

```
[SAN]
subjectAltName=DNS:<site_domain>,DNS:<www_site_domain>
```

### Preparation: create CSR

```
cd /home/zotonic/zotonic/user/sites/<site>/ssl/
openssl req -out <site>.csr -new -newkey rsa:2048 -reqexts SAN -nodes -keyout <site>.key
```

Create the CSR using the SAN extension and DER format:

```
openssl req -in <site>.csr -out <site>.csr -outform DER
```

### Run LetsEncrypt

Run the LetsEncrypt client passing the CSR

```
cd /opt/letsencrypt
./letsencrypt-auto certonly --manual --csr /home/zotonic/zotonic/user/sites/<site>/ssl/vitranslate.csr
```

### LetsEncrypt: verification

This starts a dialogue. For each domain (first root, then www), create a page at url `http://<site>/.well-known/acme-challenge/<slug>`, with content `<content>`

Because I am still doing this manually, I have created a category `acme_challenge` and created 2 pages, one for root and one for www.

Dispatch rule:

```
{acme_challenge, [".well-known", "acme-challenge", id], controller_template, [
    {template, "verifications/acme-challenge.tpl"}
]}
```

File `templates/verifications/acme-challenge.tpl` only contains `{{id.summary}}`. I paste the key from the dialog in the summary field, and the slug in the "Unique name" field.

Don't forget to do this twice, if you have a root and a www domain.


### Post processing

If all went well, the new files are stored at 

```
/etc/letsencrypt/live/<site>/
```

Copy to Zotonic:

```
cp /etc/letsencrypt/live/<site_domain>/privkey.pem   /home/zotonic/zotonic/user/sites/<site>/ssl/<site>.pem
cp /etc/letsencrypt/live/<site_domain>/cert.pem      /home/zotonic/zotonic/user/sites/<site>/ssl/<site>.crt
cp /etc/letsencrypt/live/<site_domain>/fullchain.pem /home/zotonic/zotonic/user/sites/<site>/ssl/<site>.ca.crt
cd /home/zotonic/zotonic/user/sites/<site>/ssl/
```

Make it readable by Zotonic:

```
openssl rsa -in <site>.pem -out <site>.pem
```

Make all files readable by the Zotonic user:

```
chown zotonic:zotonic /home/zotonic/zotonic/user/sites/<site>/ssl/*
```

Test if everything worked out well at `https://www.ssllabs.com/ssltest/analyze.html?d=<site_domain>&latest`


## Renewing

```
cd /opt/letsencrypt
sudo ./letsencrypt-auto renew --manual-public-ip-logging-ok
```

Then follow all steps from "LetsEncrypt: verification" above.

**Comment by mworrell** [comment]
@ArthurClemens 👍

**Comment by ArthurClemens** [comment]
3 months later...
I couldn't get manual auto-renew to work. Installed [certbot](https://certbot.eff.org) in the same folder as letsencrypt. 

This works better:

```
./certbot-auto certonly --force-renew -a manual -d www.<domain> -d <domain>
```

**Comment by jult** [comment]
Yes, certbot seems to replace the letsencrypt client [in many places](https://github.com/plesk/letsencrypt-plesk/commit/719e50a92f40789aecaa32b02e482a7127066bd3) now.

**Comment by mworrell** [comment]
Is there an Erlang version of certbot?

**Comment by mmzeeman** [comment]
To me it looks like `certbot` is the successor of the `letsencrypt` command. We can still the `webroot` method I think.

**Comment by arjan** [comment]
The easiest way we could do this is require `certbot` to be already installed. It seems it has quite a few dependencies, the one-line installer uses sudo to install a bunch of (python-related) packages, depending on the linux distro used.

**Comment by CyBeRoni** [comment]
Certbot *is* the letsencrypt client. It's just been re-named. It's still terrible and incomplete.

**Comment by mworrell** [comment]
Could we use https://github.com/gbour/letsencrypt-erlang ?

**Comment by jult** [comment]
Is there progress with this regarding mochiweb/zotonic?

**Comment by mmzeeman** [comment]
No unfortunately not.

**Comment by mworrell** [comment]
This will be on the master only - with cowboy/cowmachine.

**Comment by mworrell** [comment]
Will adapt  https://github.com/gbour/letsencrypt-erlang to Zotonic and add a module `mod_ssl_letsencrypt`

**Comment by mworrell** [comment]
Being added to #1502, using https://github.com/gbour/letsencrypt-erlang

**Comment by jult** [comment]
Been playing with this client shell script for other webservers, it's pretty amazing; https://github.com/Neilpang/acme.sh Maybe it's useful here too.

**Comment by mworrell** [comment]
Thanks, I will take a look.

In the meantime we have integrated (a slightly modified version of) https://github.com/gbour/letsencrypt-erlang into Zotonic, you can check #1502 

With this we have an admin page where you can request a certificate from Let's Encrypt. Including alternative names defined in the site's config file.

#1502 is almost ready to be merged, only some documentation issues are holding it back.
