### ISSUE TITLE
Setting is_authoritative requires use mod_admin_config permission

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1236]
Because of [this check](https://github.com/zotonic/zotonic/blob/master/src/models/m_rsc_update.erl#L704-L710). Why does `is_authoritative` depend on `mod_admin_config`?

**Comment by mworrell** [comment]
Yes, I think that check is there because non-authoritative items where meant to be inserted by system processes, like the federation.

Now that we actively incorporate linked-data sources we can remove that check.
The big difference between the two is the authoritative uri.
Which in the case of non-authoritative sources is referring to another web location.

If a resource is set to authoritative, then we might need to change the interpretation of the uri to something as *this was originally defined on this location*.
This is a point of discussion though.

**Comment by ddeboer** [comment]
I’m in favour of removing the check. 

You can always protect the `is_authoritative` yourself if you need to.

**Comment by mworrell** [comment]
I agree.

/cc @arjan
