### ISSUE TITLE
Add full edge details to edge_delete notification

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1479]
The [edge_delete](http://docs.zotonic.com/en/latest/ref/notifications/rsc.html#edge-delete) is sent *after* an edge is deleted, so the edge details can no longer be retrieved from the database. The notification, however, misses some details that can be important for observers: creator_id, created (and possibly seq).

So either:

1. send the notification *before* the edge is deleted;
2. or add the full (ex-)edge details to the notification.

Which do you prefer?

**Comment by mworrell** [comment]
If you want to send the details of the edge along, then all details need to be saved in the "deleted edge" table.  The edge_delete is sent because of a trigger which adds an entry to that table.

You should never send it *before* the edge is deleted, as the subscribers will assume the edge has been deleted and start updating views. Only after the deletion is propagated a notification should be sent.

**Comment by ddeboer** [comment]
You mean the `edge_log` table? It remains empty when edges are deleted.

**Comment by mworrell** [comment]
It is empty, because the log notification has been consumed and the notification has been sent.

**Comment by ddeboer** [comment]
Check. I’ll add the missing details to `edge_log`.

**Comment by mworrell** [comment]
It is done using a database trigger, so check there.
Maybe also investigate if it is possible to add some information about *who* deleted the edge (can we pass a psql env var?)

**Comment by ddeboer** [comment]
Yep, found the trigger.

Just adding the few details to the notification seems to make more sense, though.
