### ISSUE TITLE
Elvis whitespace configuration

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1675]
The Elvis style checker is so configured that trailing whitespace is considered an error.

I find this a bit irritating, as in Erlang it really doesn't matter if there is whitespace or not.

It also results in people configuring their editor in removing whitespace, which leads to removed EOL at end-of-file.

Can we please remove this Elvis check?

/cc @ddeboer @arjan @mmzeeman

**Comment by ddeboer** [comment]
> I find this a bit irritating, as in Erlang it really doesn't matter if there is whitespace or not.

If we follow this line of reasoning, we should have no code conventions at all and have everyone do their own thing. The import thing here is to have *some* conventions so that we can read and process each other’s code more easily. Just like using spaces instead of tabs (or vice versa), having no whitespace at EOL is a good convention. 

More to the point, Elvis is configured for a [limited selection of dirs](https://github.com/zotonic/zotonic/blob/master/elvis.config#L7). In those dirs I already cleaned up the whitespaces, so there won’t be whitespace lines on new commits in those files. Subsequently added dirs will be accompanied with similar whitespace fix commits.

**Comment by mworrell** [comment]
I just don't see the point of falling over a single space at the end of a line of code.

Don't make this bigger than it is ;)

**Comment by mworrell** [comment]
Closing for now, but keeping it around :)
