### ISSUE TITLE
Websockets and Comet

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#1741]
One thing I noticed when testing Nginx using HTTP2 in front of Zotonic, is that everything is sent sequentially over one connection, with the exception of websockets, which opens a second connection to the server. When doing simulation tests over high latency internet links, the javascript code for initiating a worst-case backup Comet connection is initiated before the websockets connection can be established.

In _mod_base/lib/js/apps/zotonic-1.0.js_ the `z_timeout_comet_poll_ajax` timer under the _Comet long poll or WebSockets_ section can be increased to `(5000)` (5 seconds). During testing this allowed enough time between Javascript being downloaded and executed, and a Websockets connection being established, which eliminates the redundant Comet process creating new connections to the server unnecessarily.

Is there a possibility that adding more time before starting a backup Comet connection could cause site functionality to break for users with low-latency connections?

**Comment by mworrell** [comment]
Indeed, we open both the Comet and Websocket connection around the same time. This is to have a quick fallback to the Comet in case the Websocket connection fails.

The moment the Websocket connection attaches to the page process on the server, we close the Comet connection. The Comet connection will then not be restarted.

In the same fashion we first test the Websocket connection before we start using it. This is because some mobile phones pretend to have Websockets, but don't send anything using it.

Only if the Websocket connection fails we will restart using Comet.

This method of using both Comet and WS is to quickly establish a working server-push connection.

**Comment by seannaswell** [comment]
Understand. Very likely then the service used to simulate low latency connections was somehow the cause. Changing the timeout did change the behavior observed, but it very well could be something peculiar with how the tests are performed...

In case it is of interest, this is what was used: https://www.webpagetest.org/
