### ISSUE TITLE
Error cowmachine_response

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1944]
`[warning] Error error:function_clause in [{cowmachine_response,send_stream_body,[{{file,2879,<<"/opt/zotonic/_build/default/lib/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-4.5.5/tiny-init.js">>},#Fun<z_file_request.8.16344269>},#{host => <<"nahodka.anriya.ru">>,ref => zotonic_https_listener_ipv4,cowmachine_resp_content_type => <<"application/javascript">>,cowmachine_cookies => [{<<"z_logon">>,<<>>},{<<"z_sid">>,<<"NFAWnmGRXiJtXNyNjQksclWCLq3I1BPL">>}],cowmachine_proxy => false,cowmachine_forwarded_host => <<"nahodka.anriya.ru">>,cowmachine_resp_body => {stream,{{file,2879,<<"/opt/zotonic/_build/default/lib/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-4.5.5/tiny-init.js">>},#Fun<z_file_request.8.16344269>}},cowmachine_resp_transfer_encoding => undefined,cowmachine_disp_path => <<"js/tinymce-4.5.5/tiny-init%7Ez_editor%7E1144918128.js">>,cowmachine_range => undefined,cowmachine_range_ok => true,scheme => <<"https">>,cowmachine_remote_ip => {159,255,12,176},path => <<"/lib/js/tinymce-4.5.5/tiny-init~z_editor~1144918128.js">>,method => <<"GET">>,cowmachine_resp_content_encoding => <<"identity">>,bindings => [{zotonic_dispatch,lib},{zotonic_dispatch_path,[<<"lib">>,<<"js">>,<<"tinymce-4.5.5">>,<<"tiny-init~z_editor~1144918128.js">>]},{zotonic_site,nahodka},{'*',<<"js/tinymce-4.5.5/tiny-init%7Ez_editor%7E1144918128.js">>}],version => 'HTTP/1.1',qs => <<>>,cowmachine_resp_code => 200,cowmachine_resp_chosen_charset => <<"utf-8">>,port => 8443,has_sent_resp => headers,cowmachine_resp_redirect => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"z_logon=; z_sid=NFAWnmGRXiJtXNyNjQksclWCLq3I1BPL">>,<<"host">> => <<"nahodka.anriya.ru:8443">>,<<"referer">> => <<"https://nahodka.anriya.ru:8443/ru/admin/edit/458">>,<<"user-agent">> => <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36">>},cert => undefined,sock => {{172,19,0,3},8443},cowmachine_site => nahodka,body_length => 0,pid => <0.1291.0>,peer => {{159,255,12,176},45654},streamid => 4,cowmachine_forwarded_port => 8443,cowmachine_remote => <<"159.255.12.176">>,cowmachine_forwarded_proto => <<"https">>,has_body => false}],[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine_response.erl"},{line,176}]},{cowmachine_response,send_response,2,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine_response.erl"},{line,56}]},{cowmachine,request_1,5,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine.erl"},{line,74}]},{cowmachine,request,4,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine.erl"},{line,55}]},{cowboy_stream_h,execute,3,[{file,"/opt/zotonic/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,249}]},{cowboy_stream_h,request_process,3,[{file,"/opt/zotonic/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,227}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
`

**Comment by mgpld** [comment]
Confirmed, same crash, but not sure about the file though.

Crash from a fresh build of dev branch.

And also the following problem that prevent zotonic:stop() to end properly:

The following error message keep trying and fail: 
11:56:59.773 [error] CRASH REPORT Process z_exometer_mqtt with 0 neighbours exited with reason: no such process or port in call to gen_server:call('z_depcache$zotonic_site_status', {get,config,mod_mqtt}) in gen_server:call/2 line 206

**Comment by mworrell** [comment]
@heiheshang are you still seeing this problem?

**Comment by heiheshang** [comment]
Yes,
but I can not update the site

**Comment by mgpld** [comment]
Same problem, compiling erlang (via kerl), version 20.0, or 20.2, or 19.3.

Symptom are; the status website comes without any design (css compilation is missing).

Tried to clean; make clean, rebuild -> failure
rm -rf _build; rebuild -> failure


The problem lies in cowmachine_response.erl, line 124 and 127: send_stream_body arguments are reversed...

`
123 send_response_bodyfun({stream, StreamFun}, Code, all, Req) ->
124     Writer = fun(FunReq) -> send_stream_body(FunReq, StreamFun) end, /// CORRECT 
124     Writer = fun(FunReq) -> send_stream_body(StreamFun, FunReq) end, /// INCORRECT
125     start_response_stream(Code, undefined, Writer, Req);
126 send_response_bodyfun({stream, Size, Fun}, Code, all, Req) ->
127     Writer = fun(FunReq) -> send_stream_body(FunReq, Fun(0, Size-1)) end, /// CORRECT
127     Writer = fun(FunReq) -> send_stream_body(Fun(0, Size-1), FunReq) end, /// INCORRECT
128     start_response_stream(Code, undefined, Writer, Req);
129 send_response_bodyfun({writer, WriterFun}, Code, all, Req) ->
` 

This fixes the issue.

**Comment by mworrell** [comment]
Good catch.

This was already fixed in the newest cowmachine. That version can not be used by the Zotonic *master* branch as it breaks some controllers. We are developing right now on the *cotonic* branch which is compatible with the newest cowmachine.

I have switch the *master* branch to a special branch of cowmachine.

Can you check if this fixes your problem?

**Comment by heiheshang** [comment]
can i try which branch?

**Comment by mworrell** [comment]
I pushed directly to master, so you can try that branch.

It will fetch a special version of cowmachine.

**Comment by heiheshang** [comment]
I'm still the same

**Comment by mworrell** [comment]
We have updated the master branch, and are now using a new cowboy, ranch and cowmachine.

Can you check if it works?
Our projects are now working.

**Comment by mworrell** [comment]
Closing for now, please reopen or file a new issue if you see any problems on the current _master_ branch.

Thanks for reporting!
