### ISSUE TITLE
Menu resource not updated when linked resource is deleted

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1951]
Scenario:

1. Add a resource to a menu
2. Delete this resource (not from the menu but really delete)
3. Check base/export resource is still in the `menu {}` part

Visually the item is removed from the menu. 

I see this was reported earlier in #291.

**Comment by mworrell** [comment]
The same holds for any resource that is referenced from with the *blob* of a referring resource. Think of images, links, and blocks.

The way this is resolved runtime is that, on display, the deleted menu item is hidden by the access control checks.

You could discuss if the resource should be updated when a contained item turns out to be deleted. For now I prefer to resolving the problem *runtime* and discard non existent (or invisible) resources.

**Comment by mworrell** [comment]
So, in short, we prefer to have a lazy solution where the menu is updated on fetch.
This also reflects the behavior for inaccessible or unpublished menu items.

Alternative would be to have an edge for every menu item in the resource and then update the menu if the edge's object is deleted.

Closing for now.
