### ISSUE TITLE
Cannot select category 'category' in new upload modal

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2089]
In some cases i would like to link to a category (search filters categories for example), but i cannot select find them anymore. Even if i search for id:category_name the resource does not show up in the results.

**Comment by mworrell** [comment]
Looked into this.

I think it is because we only show categories on which the current user has "insert" rights. Which for most users is only a subset of the categories on which she has "link to" rights.

We have a couple of options here:

 1. Show a separate category filter above the list of search results (this could be linked to the category in the create), this should show all content we can link to.
 2. Show all categories but disable the `create` button if the user doesn't have insert permission

I am leaning towards option 1.

The search on `id:...` is separate from the above and should be intercepted in the search.

**Comment by DorienD** [comment]
I agree with option 1.

**Comment by mworrell** [comment]
Then we are agreeing and we will go with showing a separate (linked _from_ the create but not _to_ the create) category drop down filter.

**Comment by mworrell** [comment]
@DorienD can you give this a test drive?

**Comment by DorienD** [comment]
Works!

**Comment by mworrell** [comment]
Thanks for checking!
