### ISSUE TITLE
can't compile in docker

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2709]
`make: Entering directory '/opt/zotonic/_build/default/lib/bcrypt/c_src'
make: uname: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: mkdir: Operation not permitted
make: *** [Makefile:73: ../priv/bcrypt_nif.so] Error 127
make: Leaving directory '/opt/zotonic/_build/default/lib/bcrypt/c_src'
`

**Comment by mworrell** [comment]
Permissions biting Docker again.

Is this the same as https://github.com/zotonic/zotonic/issues/2328 ?

**Comment by mworrell** [comment]
An option could be to not use the host system anymore at all and completely run Zotonic inside the container.

Of course editing files inside the container is then left as an exercise to the user....  or we could map apps_user to the host.

**Comment by mworrell** [comment]
Then we still will run into problems with creating new sites from the UI - unless we set apps_user permissions to 777.

/cc @ddeboer maybe you have an idea?

**Comment by heiheshang** [comment]
> Permissions biting Docker again.
> 
> Is this the same as #2328 ?

bash-5.1$ ls -l /opt/zotonic/_build/default/lib/bcrypt/c_src/
total 68
-rw-r--r--    1 zotonic  nogroup       2883 Jul 16 11:44 Makefile
-rw-r--r--    1 zotonic  nogroup       3480 Jul 16 11:44 async_queue.c
-rw-r--r--    1 zotonic  nogroup       2867 Jul 16 11:44 async_queue.h
-rw-r--r--    1 zotonic  nogroup       7950 Jul 16 11:44 bcrypt.c
-rw-r--r--    1 zotonic  nogroup       7138 Jul 16 11:44 bcrypt_nif.c
-rw-r--r--    1 zotonic  nogroup        768 Jul 16 11:44 bcrypt_nif.h
-rw-r--r--    1 zotonic  nogroup       6354 Jul 16 11:44 bcrypt_port.c
-rw-r--r--    1 zotonic  nogroup      23322 Jul 16 11:44 blowfish.c
-rw-r--r--    1 zotonic  nogroup       3684 Jul 16 11:44 erl_blf.h

no that's another problem

**Comment by mworrell** [comment]
When I try on Ubuntu, in Parallels, (even with sudo) I get this:

{"init terminating in do_boot",{{badmatch,{error,{shutdown,{{exit,{stream_to_file_failed,eacces}},[{httpc_handler,start_stream,3,[{file,"httpc_handler.erl"},{line,1507}]},{httpc_handler,handle_http_msg,2,[{file,"httpc_handler.erl"},{line,936}]},{httpc_handler,handle_info,2,[{file,"httpc_handler.erl"},{line,283}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}}},[{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,453}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}

So, also an access-denier error, but even earlier.

I was checking if we could start using this: 

https://vsupalov.com/docker-shared-permissions/

And then build our own image.

BTW bcrypt has been changed to use relative paths, this because the abs paths can contain spaces (especially on macOS).

**Comment by heiheshang** [comment]
i think it has to do with the alphine image
with the rights, everything is fine with me, the rights in the container and on the host machine are the same

**Comment by heiheshang** [comment]
https://github.com/alpinelinux/docker-alpine/issues/146
maybe this is our problem

**Comment by heiheshang** [comment]
figured it out. The problem is in the docker version, put the latest version and everything compiled without problems

**Comment by mworrell** [comment]
Good find.

What do you think, should we:

1. Leave it as it is; or
2. Make an Ubuntu based image, with the uid/gid set right; or
3. Place everything in the container, not making use of the host file system?

**Comment by heiheshang** [comment]
it is better to leave it as is, just add the uid/gid
alpine gives an easy image
if you put everything in the image, then how will you update the zotonic files from the repository?
users will be forced to rebuild the image to receive updates

**Comment by mworrell** [comment]
> if you put everything in the image, then how will you update the zotonic files from the repository?

Indeed, that is why I thought that it is better to have at least the source files on the host.

Agree totally with the uid/gid - those are creating a big mess.

The `_build` directory could be on the image though.

Maybe these mapped from the host:

 - apps
 - apps_user
 - data (all site data)
 - logs (console.log etc)
 - config (should then contain the zotonic.config and other config files

Maybe such an setup would also make it better?

That is, if the data on the container is persisted - otherwise you need to rebuild Zotonic every single time.

**Comment by heiheshang** [comment]
_build cannot be in image, everything inside the image is created when the image is created. If you are doing a git pull, you need to rebuild the _build directory, but after creating the image, everything you change will exist until the container is stopped. Changes will not be saved unless you docker save

**Comment by mworrell** [comment]
Then we could have `_build` inside the image, so that if we do a *make* then all build artifacts are stored inside the container and not placed on the host system.

Still a question if we want to have all uploaded files inside the container or on the host. What would you prefer?

**Comment by heiheshang** [comment]
if you don't need these files you can store them in a container.

**Comment by heiheshang** [comment]
for debugging, the sql database can be run in a container, but for work this is not the best option, you will lose performance due to sys call sql server -> docker -> host computer

**Comment by mworrell** [comment]
I agree, having a db in a container is a performance problem. With the current docker-compose we are doing that however. Are you running using compose?  Or only erlang (et al) in a container and the db on your host?

**Comment by heiheshang** [comment]
for high-load projects, we put postgreSQL separately, not in a container. We run Erlang via docker -composer, so we do not depend on the host system.
for development, containers are convenient to use.

**Comment by mworrell** [comment]
I have now a fix for the user/group ids in https://github.com/zotonic/zotonic/pull/2714

This also simplifies the mounts, and puts all data (including logs, mnesia and configs) in the docker-data directory.

**Comment by mworrell** [comment]
Note that the config directory is now moved to `docker-data/config`

And that all data and logs are also place in the `docker-data` directory.
