### ISSUE TITLE
mod_email_status: Clear email errors after 72 hours

### ISSUE THREAD

**Issue by michielklonhammer** [zotonic/zotonic#3946]
When sending email  from Zotonic (via Mailgun), a "Retries exceeded" email sets a permanent error message.
If new mails do not cause errors, this error message should be cleared (at least after 72 hours).
Now (in LearningStone) the user has to set an error message.

**Comment by mworrell** [comment]
Cause of the failure is an error in the encoding of some headers.
I've added extra logging in #3947 

As an extra we can add a periodic task in mod_email_status to clear sending errors if:

 * An email has been successfully sent after there error last occurred
 * There have been 72 hours since sending the email

**Comment by mworrell** [comment]
Actually there is some retry logic.

If an email is sent after an error occurred, and there wasn't a bounce within 4 hours, then the email address if flagged as ok.
(If the address was not blocked.)
