### ISSUE TITLE
Add support for language variations like zh-hk

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#499]
It would be good to have support for more specific locales like zh-hk but also en-us, en-gb, etc.

Lets have this ticket as a discussion on how to do that and what that means for the po files, fallback mechanism (?), etc.

**Comment by ArthurClemens** [comment]
This branch contains a fairly efficient lookup of a language fallback. It is called when a translation cannot be found for the current language. In the current Zotonic, only `en` is considered as hardcoded fallback. The code changes make it possible to define a specific fallback per language, thus progressing one step towards region specific language settings like "fr-be” and "zh-tw”.

The major code change is that `#context.language` now contains a list of language code atoms, instead of a single language code. The first list item is the selected language. To keep other code working as the same as possible, `z_context:language/1` will still return the selected language.
Other code that directly read `Context#context.language` has been replaced with the `z_context:language/1` function call.
`z_context:set_language/2` accepts an atom and puts it in the list, but it will also take a list. That list will be set by `mod_translation` when a language has defined a fallback language.

Translation lookup takes one more lookup in case no translation is found. Fallback lookup is not recursive: only the fallback of the current language is explored. This also removes the need to program against infinite loops.
Currently only 1 fallback is considered, but it is built with a list of fallbacks in mind.
The ultimate fallback is `en` and that functions as it does today.

It looks like there is an obsolete function `z_trans.erl:lookup_fallback_language` that is called by `filter_language`.

**Comment by mworrell** [comment]
Nice work! And we shouldn't be poking directly into the Context#context.language anyway.

:+1: for merging

**Comment by ArthurClemens** [comment]
Things left to do on this issue:

1. Add more languages to `i18n/iso639.erl`, possibly use https://github.com/bdswiss/country-language/blob/master/data.json or http://www.localeplanet.com/icu/iso639.html
1. Change `i18n/z_trans:is_language` to relax the check on 2-letter codes.
1. It seems that the url can only have a 2-letter language code.
1. Check `.po` generation
1. Check filters/scomps

**Comment by mworrell** [comment]
Ad 3: that is also handled by mod_i18n, it can be easily changed to also accept ``xy-...`` prefixes, waarbij ``xy`` then a valid ISO code is and we add a max length to the language variation.

Do we also want to be able to handle languages like ``x-klingon`` ?

**Comment by ArthurClemens** [comment]
The Mozilla L10n project uses this guideline:

To summarize, these schemes are supported:

* ab
* ab-XY
* abc-XY
* abc-XY-SIL
* abc-XY-dialect

where

* ab/abc - from [ISO 639.1/639.2](http://www.loc.gov/standards/iso639-2/)
* XY - from [ISO 3166](http://www.iso.org/iso/en/prods-services/iso3166ma/02iso-3166-code-lists/list-en1.html)
* SIL - from the [SIL list](http://www.ethnologue.com/codes/)
* dialect - following the rules from [RFC 4646](http://www.ietf.org/rfc/rfc4646.txt) (5 to 8 letters; or a number followed by three letters or numbers)

https://wiki.mozilla.org/L10n:Locale_Codes

**Comment by ArthurClemens** [comment]
A useful tool might be https://github.com/flitbit/erlang_bcp47

**Comment by ArthurClemens** [comment]
I am working on this.

One of the code changes is to allow "zh-hk" in the URL, instead of "zh_hk". In `mod_translation` I am therefore removing `z_string:to_name()`. Am I missing something important?

**Comment by mworrell** [comment]
As long you only use sanitized values, or only accept values on a whitelist, then removing the `to_name` is no problem.

**Comment by ddeboer** [comment]
@ArthurClemens Feel free to post your work in progress in a PR so @alvaropag and others can have a look at it and help out.

**Comment by ArthurClemens** [comment]
Any idea why we still need `mod_translation:do_choose`? I am largely ignoring it because it simplifies "en-us" to "en", the opposite of what I want. It is called in `try_set_language`: "Set the language of the user. Only done when the found language is a known language.". Now (in the pull request) we have a finite set of languages, so you could argue that all listed languages are known languages.

**Comment by ArthurClemens** [comment]
I need help with the translation tag. To support language codes such as 'pt-br', changes are need to the template compiler to work:

```
{% _ "Example" 'pt-br'="português - Brasil" %}
```

or 

```
{% _ "Example" ptbr="português - Brasil" %}
```

**Comment by arjan** [comment]
What about `pt_br=`?

**Comment by ArthurClemens** [comment]
That’s an option too.

**Comment by mworrell** [comment]
It is quite usual to have `pt_br` in program code, and `pt-br` in urls.
(Let's keep it all lowercase?)

**Comment by ArthurClemens** [comment]
Yes, let's keep it lowercase.

I've been pondering about the types to use. This is the current state:

* Language codes (and other language data) are binary strings;
* In the language config the language objects are stored with binary strings as keys;
* The selected language in the global Context is an atom, as well as the fallback language.

There is something to say for keeping all language in code as atoms. That would mean that the keys in the language config would be atoms too.

**Comment by ArthurClemens** [comment]
When the URL shows a language, shouldn't that language override the user setting?

**Comment by ArthurClemens** [comment]
I don't understand https://github.com/zotonic/zotonic/blob/master/modules/mod_translation/mod_translation.erl#L198. The code seems to assume that "id" can be a valid language. If true, it sets `z_language` to "id". How is this used?

**Comment by mworrell** [comment]
That check on `id` is a hack. The reason is that there is that there is a dispatch path `id/1234` but also the language `id` (Indonesian). This code recognizes `id/1234` and then ignores `id` as a language.

**Comment by mworrell** [comment]
About the language in an URL, yes it should override the user setting, unless we are logging on the user, in that case we might want to switch to the user's language.

**Comment by ArthurClemens** [comment]
I overlooked Indonesian. I have added a clarification to the code.

**Comment by mworrell** [comment]
Wondering if we can close this, as the language-variations have been merged into master?

**Comment by ArthurClemens** [comment]
I believe so.
