### ISSUE TITLE
Translations: easier translation by combining modules in one .po file

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#858]
I propose to combine all .po files from the modules into a single .po file per language.

This file could be located in `~/priv/translations/xx.po` (where xx is the iso language code).

This would make it easier to translate the core Zotonic into different languages as there is an overlap between the different modules and managing a single .po file is easier than the current situation of a .po file per module.

Additionally: after generating a new .pot file we can automatically merge that .pot file into the language .po files.

Comments?

/cc @arjan @mmzeeman @kaos @michielklonhammer

**Comment by mworrell** [comment]
`mochiweb` has a module `mochifmt` which implements Python like string formatting for Erlang.

Maybe @arjan and @ArthurClemens you can have a look if that fits what you like and expect?

**Comment by ArthurClemens** [comment]
I've played a little bit with the `format` function, and it does solve my main need.

I am very happy that named variables are supported. Normally you would write such a message string:

```
Str = "{0} was renamed or moved from {1} on {2} by {3}"
```

But that makes it hard for translators to understand the right order (for instance if the translation would be "on {2} {1} was renamed or moved to {0} by {3}" - the translator would need to dig into the code to see what the numbers mean).

A solution to this problem is named variables:

```
Str = "{new} was renamed or moved from {old} on {date} by {user}",
OldName = "Summer",
NewName = "Autumn",
DateStr = qdate:to_string("Y-m-d H:i:s", calendar:universal_time()),
User = "me",
lager:info("~p", [
    string:join(
        mochifmt:format(Str, [
            {new, NewName},
            {old, OldName},
            {date, DateStr},
            {user, "me"}
        ]),
    "")
])
```

which outputs:

```
"Autumn was renamed or moved from Summer on 2015-02-24 00:15:17 by me"
```

It would be great to use this.

**Comment by ddeboer** [comment]
So to come back to the original question of combining translation files, what we need to do is this:

1. Remove the individual `.po` files in the core module directories.
2. Change the ‘Generate `.pot` file’ functionality to generate one combined `.pot` for core modules. 

@mworrell Does this sound about right?

**Comment by arjan** [comment]
yes, seems logical.

**Comment by michielklonhammer** [comment]
Yes, works better like we did with LearningStone. Are the forms part of
core modules?



*From:* David de Boer [mailto:notifications@github.com]
*Sent:* Monday, June 20, 2016 6:24 PM
*To:* zotonic/zotonic <zotonic@noreply.github.com>
*Cc:* michielklonhammer <michiel@klonhammer.nl>; Mention <
mention@noreply.github.com>
*Subject:* Re: [zotonic/zotonic] Translations: easier translation by
combining modules in one .po file (#858)



So to come back to the original question of combining translation files,
what we need to do is this:

   1. Remove the individual .po files in the core module directories.
   2. Change the ‘Generate .pot file’ functionality to generate one
   combined .pot for core modules.

@mworrell <https://github.com/mworrell> Does this sound about right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zotonic/zotonic/issues/858#issuecomment-227193402>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABPxEYOC7yuoGeVJukDkDoCabN_519Pcks5qNr6zgaJpZM4Cz0Zv>
.

**Comment by mworrell** [comment]
@michielklonhammer I suppose with *forms* you mean mod_survey?  Yes that is part of the core modules.

**Comment by mworrell** [comment]
@ddeboer Yes sound logical.  Shall we place the `.po` and `.pot` files in `priv/translations` ?

We should take care of only combining the translations of all core modules, and not of the user modules and sites.

**Comment by mworrell** [comment]
For step 3, that can be handled by the po merge tools.

**Comment by ddeboer** [comment]
@mworrell Agreed on both points (edited above).

**Comment by mmzeeman** [comment]
FYI 

We are picking up translation of our service in 9 languages. We want to use our crowdin account again. See: https://crowdin.com/ 

This is an external service, easy to use service, which allows non-technical users to contribute translations. It has an api to upload and update po files. It maybe an idea to look into that too.
