### ISSUE TITLE
Safari 8 cookie bug and OAuth redirects

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#902]
There is a problem with the default security settings of Safari 8.
It does not give the cookies to the site being redirected to, which of course give major problems.

In the case of LinkedIn the whole OAuth token handling is broken.
Facebook seems to have found a workaround on their end.
Twitter always shows the authentication dialog.

The workaround for Safari users is to relax their cookie settings:

![83bf83a6-63ad-11e4-96aa-3c18b9af1eed](https://cloud.githubusercontent.com/assets/38268/5646695/451d9c32-967f-11e4-80fc-913d5e8b483e.jpg)

For another discussion of this issue see also: 
https://github.com/drone/drone/issues/663#issuecomment-61565820

**Comment by mikepb** [comment]
A JavaScript redirect seems to work for OAuth:

```html
<script> window.location.href += "&reloaded"; </script>
```

Just make sure not to do an infinite loop...

**Comment by MattiSG** [comment]
@foresmac Thank you so much for having documented this.
I don't know where we could keep this conversation going

**Comment by foresmac** [comment]
No, it's a bug between OAuth and the way Safari handles a more secure option in Safari 8. I only found it because I prefer the more restricted cookie handling, but it breaks most OAuth implementations. I ended up just switching back to "Allow from websites I visit" and, while I would prefer the more restricted option, I no longer have OAuth problems.

**Comment by MattiSG** [comment]
> it breaks most OAuth implementations

Really? Twitter and LinkedIn still work here!

**Comment by foresmac** [comment]
IIRC, some places have implemented workarounds that store cookies in a way that works with the more stringent requirements.

**Comment by mworrell** [comment]
@foresmac can you remember/find what that way might be?

**Comment by foresmac** [comment]
I don't have details on that; just chatter I've heard. I don't deal directly with FE stuff that often so to be fair my understanding is not complete.

**Comment by mikepb** [comment]
I found that using a client-side page refresh forces Safari to submit the cookies, even with the most restrictive setting. The Location header works. The Refresh header and associated META tag work. JavaScript refresh works. I add a `refresh=1` URL query parameter and a server check to avoid infinite refresh loops.

**Comment by mworrell** [comment]
@mikepb With the "Location header works," do you mean that a server-side redirect also solves the problem?

**Comment by mikepb** [comment]
Yes, in my limited localhost testing, it seems like it does.

**Comment by jlukic** [comment]
Hey I've ventured over here from a google search. Apologies since I know this is not related to Zotonic. Did you ever find a permanent solution to Safari 8 oauth logins? 

@mikepb In what step exactly are you using the client side page refresh? Im not having any luck with this solution.

**Comment by mikepb** [comment]
This is what I'm using and it works great with Stripe, though the stricter Safari setting forces me to sign in to Stripe every time.

```js
  app.get("/connect/stripe/callback", function* (next) {

    // workaround for Safari "Allow from current website only" cookie setting
    if (this.session.isNew && !("ok" in this.query)) {

      // set the Refresh header
      this.set("Refresh", `0; url=${url}`);

      // send a page with meta-refresh and JavaScript refresh
      return yield this.render("refresh", { href: url });
    }

    // exchange access code for access token
    var result = yield request.post({
      url: STRIPE_TOKEN_URL,
      form: {
        grant_type: "authorization_code",
        client_secret: options.secret_key,
        code: this.query.code
      }
    });

    // parse body
    var auth = JSON.parse(result.body);

    // do stuff with OAuth data...

  });
```

**Comment by haavar** [comment]
I was looking at a similar issue today. I could not find any difference in the cookies, but there was a difference in the origin header. In our case, Firefox and Chrome was not sending the origin header, but Safari was.

In our case the root cause was a CORSE filter on the OAuth server.

You could be facing the same issue, since a java-script reloading the page would probably change the origin header.

**Comment by ptoomey3** [comment]
I opened a radar about this a while back. And, it sounds like it is a bug that is supposedly fixed in the public beta of the next OS release: https://bugs.webkit.org/show_bug.cgi?id=139683

**Comment by ytrezq** [comment]
@ptoomey3 : Sorry for telling it here, but may you check your e‑mails replies please ?

**Comment by rafaelbiriba** [comment]
Any update ??

I got a redirect problem using "omniauth-oauth2 -> 1.1.1" and "omniauth -> 1.1.3".

Only in safari 8, when the login start (click login button), the redirect to the authorizer die in the lightbox (js error: "Failed to load resource: resource unavailable").
Calling direct the oauth url "/auth" to start the transaction, the redirect dies too with error "Safari can't open the page 'authorizer_url...' "

What to do ?

**Comment by ptoomey3** [comment]
The only option I'm aware of are:

* Require people to update to the latest OS X release. 
* Use a JavaScript redirect instead of a 302. 
* Use a meta refresh redirect instead of a 302. 

We (GitHub) switched our OAuth redirect logic to use a JS redirect (since it was faster than a meta refresh), falling back to a meta refresh if JS is disabled. 

It doesn't look like Apple has any intent to backport the fix to older OS releases, so a workaround is the only option if you want to support all Safari users.

**Comment by jlukic** [comment]
@ptoomey3 Thanks, very helpful

**Comment by ptoomey3** [comment]
I spoke too soon :smile:, as I had completely forgotten about a bug that cropped up after we
made the change to support all Safari uses. Not long ago we came across an internal application that relied on fetching images from an OAuth application as a subresource (think authenticated requests to an endpoint generating graph images). If a user hadn't visited the graphing application for some time their session was invalid and the image request would trigger an OAuth dance. And, as it turns out, it doesn't look like subresource requests will follow a meta refresh redirect. So, we had effectively broken functionality for other browsers. As a result, we ended up having to revert the workaround we had in place. We still use a meta refresh for oauth redirects (only on HTTP posts), but it has nothing to do with Safari anymore (we use it for `form-action` compatibility for content security policy). So, I'm not sure there is any great solution that is 100% compatible. Sadly, the only real fix seems to be reducing privacy settings in Safari on older releases of OS X.

**Comment by mworrell** [comment]
Closing this, as it is a problem for older Safari versions.

**Comment by ytrezq** [comment]
@mworrell : version 8 was the latest version before 2015. Did you checked first if current versions are affected first ?

**Comment by mworrell** [comment]
@ytrezq With Safari 12 (and previously in 11) we don't see any problems. We also don't receive any questions from customers.
