### ISSUE TITLE
Error gmake FreeBSD (bash needs --import functions)

### ISSUE THREAD

**Issue by wowi42** [zotonic/zotonic#905]
Hi,
I have an error when I try to install zotonic on FreeBSD : 
```
{14:13}~/zotonic-release-0.12.3 ➭ gmake
erl -noshell -s inets -s ssl \
  -eval '{ok, saved_to_file} = httpc:request(get, {"https://github.com/rebar/rebar/wiki/rebar", []}, [], [{stream, "./rebar"}])' \
  -s init stop
chmod +x ./rebar
EXOMETER_PACKAGES="-afunix -netlink -exo +setup" ./rebar -C rebar.config.lock get-deps
ERROR: Failed to load /usr/home/loic/zotonic-release-0.12.3/rebar.config.lock: {error,
                                                                                {11,
                                                                                 file,
                                                                                 {error,
                                                                                  {badmatch,
                                                                                   []},
                                                                                  [{erl_eval,
                                                                                    expr,
                                                                                    3,
                                                                                    []}]}}}
GNUmakefile:54: recipe for target 'get-deps' failed
gmake: *** [get-deps] Error 1

```
no idea why, sorry...
Peace

**Comment by mworrell** [comment]
Hi,

Did you find a solution or reason for the problem?

- Marc

**Comment by wowi42** [comment]
Hi,
no I didn't find any (and I didn't search a lot, sorry :-1: )

**Comment by mworrell** [comment]
I will check if we find some "volunteers" with a BSD machine.

**Comment by okc0mputer** [comment]
I get that same error on FreeBSD 10.1 with erlang 17.4, except it can't open rebar.config as opposed to rebar.config.lock. Consider me a volunteer

**Comment by arjan** [comment]
On master, `rebar.config` is used in our build system; on the release branches, it's `rebar.config.lock`.

**Comment by arjan** [comment]
I just tried with building on FreeBSD 10 and I dont get any build errors.

`FreeBSD xxxx.xxxxx.nl 10.0-RELEASE-p17 FreeBSD 10.0-RELEASE-p17`

**Comment by mworrell** [comment]
I vaguely remember some rebar issues with a 17.x branch?
Maybe the issue is there?

**Comment by arjan** [comment]
Maybe.. I tested with R16 on FreeBSD.

**Comment by okc0mputer** [comment]
I fudged My last reply...
I’ve been using R17 on OS X, and all the rebar dependencies seem to install without problems.  Then again, i’m having a lot of trouble getting zotonic going on OS X in general but thats not related to make or rebar, etc.  On FreeBSD (g)make/rebar will not complete:

(This was from 0.13-dev, on 0.12.4 its the expected rebar.config.lock)
ERROR: Failed to load /usr/home/okcomputer/zotonic/rebar.config: {error,
                                                                  {11,file,
                                                                   {error,
                                                                    {badmatch,
                                                                     []},
                                                                    [{erl_eval,
                                                                      expr,3,
                                                                      []}]}}}

This same error occurred using 0.12.4 and 0.13-dev, (FreeBSD-10.1-RELEASE)
I’ve tried replacing the rebar from FreeBSD ports with the GIT release with no luck,  the only thing I haven’t done is to try a different erlang version, but other users have reported this issue with R16, so i’m not going to bother.  I’m new to erlang and to zotonic, so I don’t really know where to go from here.  If needed, I can make a user account on my freebsd VPS for someone more experienced with erlang to experiment on.
--  
John Marcus
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by mworrell** [comment]
Interesting.

@arjan, maybe you could check with R17 (maybe via kerl)?

(BTW curious about your OS X problems - maybe put those in another ticket?  We are all using OS X, and afaik didn't encounter any major obstacles)

**Comment by arjan** [comment]
no the only FreeBSD machine I have access to is a production server and I'd rather not mess with it anymore than I already have..

**Comment by mworrell** [comment]
ok, then we need to install a FreeBSD VM

**Comment by 4436** [comment]
Hello, Arjan, Mark, I posted about this to the google groups list for zotonic users, and I also notice that you discussed the issue here.  Same problem on FreeBSD 10, an actual machine:

# uname -a
FreeBSD ... 10.1-RELEASE FreeBSD 10.1-RELEASE #0: Thu Mar 26 19:10:31 UTC 2015     
/usr/obj/usr/src/sys/ALTQGEN  amd64

That's a recent FreeBSD 10 release with a modified kernel for ALTQ for the pf firewall.

I removed the stock Erlang 17, and installed from the source tarball at http://www.erlang.org/:

otp_src_R16B03-1.tar.gz

Which runs fine:
$ erl
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

# gmake
EXOMETER_PACKAGES="-afunix -netlink -exo +setup" ./rebar -C rebar.config.lock get-deps
ERROR: Failed to load /usr/local/src/zotonic-0.12.4/rebar.config.lock: {error,
                                                                        {11,
                                                                         file,
                                                                         {error,
                                                                          {badmatch,
                                                                           []},
                                                                          [{erl_eval,
                                                                            expr,
                                                                            3,
                                                                            []}]}}}
GNUmakefile:54: recipe for target 'get-deps' failed

same result with remake:

/usr/local/src/zotonic-0.12.4 # remake
##>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
EXOMETER_PACKAGES="-afunix -netlink -exo +setup" ./rebar -C rebar.config.lock get-deps
##<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
ERROR: Failed to load /usr/local/src/zotonic-0.12.4/rebar.config.lock: {error,
                                                                        {11,
                                                                         file,
                                                                         {error,
                                                                          {badmatch,
                                                                           []},
                                                                          [{erl_eval,
                                                                            expr,
                                                                            3,
                                                                            []}]}}}
GNUmakefile:53: *** [get-deps] Error 1

#0  get-deps at /usr/local/src/zotonic-0.12.4/GNUmakefile:53
#1  all at /usr/local/src/zotonic-0.12.4/GNUmakefile:25
Command-line invocation:
        " none

I thought I would try to see if 0.9 would build, and got this:

/usr/local/src/zotonic-release-0.9.1 # gmake
cd deps/lager && ./rebar compile
./rebar: not found
GNUmakefile:21: recipe for target 'lager' failed
gmake: *** [lager] Error 127

So Arjan did it build for you on FreeBSD 9 with erlang R16?  That's great, but frustrating if FreeBSD change the gmake or set for 10.

I also have a FreeBSD VM.  Let me know what else I should try.

Thanks,

Gordon

**Comment by mworrell** [comment]
@4436 we do fetch `rebar` in the Makefile, did the `gmake` not pick up on that rule in the Makefile?

**Comment by arjan** [comment]
We should try to reproduce this. I suspect this is an issue in rebar.

**Comment by 4436** [comment]
Marc, I'm installing FreeBSD 9.3 in VMWare to see if it's the same result.  How would I check to see if gmake (and remake) are missing the fetch command in rebar?  rebar is new to me, but it looks like an erlang fetch-make-compile script.  Is that right?  FreeBSD lets you load a system wide rebar, which is helpful, but maybe it conflicts with the zotonic script (probably not, just a thought).  Gmake seems to be saying that it cannot load:

<<
ERROR: Failed to load /usr/local/src/zotonic-0.12.4/rebar.config.lock: 
>>

So the make file is pointing it to the correct rebar file.  But I don't know how to debug rebar, which might be failing within the call from the make file.

Arjan, I'll try to install this in FreeBSD 9.3 on a VM and see if it happens again.  But if you got zotonic running on FreeBSD 10, that would be good to know.  From the lists it appears that earlier versions of FreeBSD did fine with zotonic.  So if R15 works with 8 and 9, I can try them.

I will also try to install Nirtrogen with webmachine, which also uses rebar.  If that fails as well, it might be something about FBSD 10.

Thanks,

Gordon

**Comment by 4436** [comment]
OK; progress with FreeBSD 9.3.  The attached screen shots show:

./bin/zotonic -debug running (zotonic starts and listens) on:
erlang 17 (erl-17, erts 6.3.1) on:
FreeBSD 9.3 (uname -a)

The only difficulty this is in a VMWare guest.  The only difficulty was that gmake is unaware if git or curl is installed, and fails without them.  So before running gmake on FreeBSD do this:

pkg install git
pkg install curl

I installed git and curl on the FreeBSD 10 machine (git was already there, curl was not).  With both installed I got the same error message as before.

So it may be peculiar to FreeBSD 10.  The good news is that it does indeed install on FreeBSD 9.3.

I can keep experimenting with the FreeBSD 10 machine, but I have to get it running sooner rather than later.  So I'll be putting FreeBSD 9.3 on the server tomorrow.  If there's anything else you would like me to try on FBSD 10, let me know and I'll try it on a FreeBSD 10 virtual guest in VMWare.

Many Thanks,

Gordon

![bin-zotonicd-debug](https://cloud.githubusercontent.com/assets/661212/6955577/2ea328ba-d8a5-11e4-8113-e432dedfa65a.png)
![erl-17](https://cloud.githubusercontent.com/assets/661212/6955578/2ea73b08-d8a5-11e4-990b-546aa41cfb12.png)
![uname-a-freebsd9-3](https://cloud.githubusercontent.com/assets/661212/6955579/2eaabd6e-d8a5-11e4-8a2b-afe8bc9d5afd.png)

**Comment by mworrell** [comment]
Good progress, and interesting.  I will have a look at it and maybe coming week (sorry very busy) check with a FreeBSD VM on parallels.

**Comment by wot123** [comment]
I think it's something to do with a shellshock fix to bash in FreeBSD. It wont work without the --import-functions flag for bash, I got it working by rebuilding bash from ports and turning on the 'Import function from env without --import-functions' option, though I've no idea what the security implications of doing this are :)

**Comment by okc0mputer** [comment]
Thanks for the info.  I came to almost the same conclusion as you via different methods.  I had temporarily given up on zotonic when I stopped being able to compile erlang  on os X, which just randomly started happening a few months ago.  A few OS X  versions later, and I was having strange problems with almost every command line app.  I had a version of csh installed and after switching shells, most of my command line issues went away.  It is definitely a bash related issue, I just couldn’t find anything in .profile or .bash_profile that would be causing bash to act so strangely.  My solution was to back up my data, reinstall os X from the recovery partition, and now things are working.  I easily compiled erlang from git sources last night, and am looking to see what happens when i try running zotonic.  I’m no expert in erlang, but I’ve been compiling it from source for about a year as I learn the language, and this was the first time I had any problems with erlang or erlang software that i didn’t bring upon myself.  I’m assuming zotonic should run without too much fuss now, but we’ll see once i get home...  
Thanks,
--  
John Marcus
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by bksta** [comment]
I recompiled bash with --import-functions=on. This allowed gmake to get further in the process but it still failed here:

==> edown (compile)
Compiled src/edown_make.erl
Compiled src/edown_lib.erl
Compiled src/edown_xmerl.erl
/usr/home/bksta/zotonic/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
/usr/home/bksta/zotonic/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
Compiling /usr/home/bksta/zotonic/deps/edown/src/edown_doclet.erl failed:
ERROR: compile failed while processing /usr/home/bksta/zotonic/deps/edown: rebar_abort
GNUmakefile:60: recipe for target 'compile-deps' failed
gmake: *** [compile-deps] Error 1

with: 
FreeBSD 10.1
Erlang/OTP 18 [erts-7.0]
GNU Make 4.1 Built for amd64-portbld-freebsd10.1
GNU bash, version 4.3.39(0)-release (amd64-portbld-freebsd10.1)

**Comment by wot123** [comment]
Could be related to this:
https://github.com/esl/edown/issues/32

Might be worth just trying it again.

I just did a fresh build and it worked so I can't help.

**Comment by CyBeRoni** [comment]
I just ran into this problem, presumably, given the error is identical, on linux. It started working once I installed bash.

Apparently some part of this system requires bash? I would consider that a huge bug.

**Comment by ddeboer** [comment]
Follow-up in #1365.
