### ISSUE TITLE
Bootstrap glyphicon paths

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#939]
Hi!

If we have a lib tag like so:

```
{% lib
    "bootstrap/css/bootstrap.min.css"
    "css/build/screen.css"
%}
```

Bootstrap cannot find the glyphicon fonts it includes trough a relative path: (../fonts/glyphicons-halflings-regular.eot)

If i give the bootstrap its own lib tag it does find the relative paths to the glyphicon font.

```
{% lib
    "bootstrap/css/bootstrap.min.css"
%}
{% lib
    "css/build/screen.css"
%}
```

Apparently in the admin bootstrap the paths are absolute, but in the mod_bootstrap they are not.

**Comment by mworrell** [comment]
In the admin the paths are absolute `/lib/css/...`

Is this something that can be configured in the css generation?

@arjan @ArthurClemens

**Comment by ArthurClemens** [comment]
Without having looked at the path setting...

The font files are relative to the CSS file. So for the url `../fonts/glyphicons-halflings-regular.eot` the font directory is one level higher than the CSS.

**Comment by mworrell** [comment]
The problem is that if the bootstrap.css file is combined in a single `{% lib %}` tag that the relative path is not correct anymore.

Is it possible to re-generate the css files with an absolute path?
And if so, what are the generation commands (do we have some docs :) )

**Comment by ArthurClemens** [comment]
I can confirm that placing bootstrap in its own `{% lib %}` tag makes the linking to glyphicons work.

Looking at mod_base_site, if all CSS is combined, I get this link tag:

```
<link href="/lib/bootstrap/css/bootstrap~bootstrap-base-site~/css/jquery.loadmask~z.icons~z.growl~z.modal~z.icons~site~2850570656.css" type="text/css" media="all" rel="stylesheet">
```

and using separate lib tags:

```
<link href="/lib/bootstrap/css/bootstrap~148506649.css" type="text/css" media="all" rel="stylesheet">
<link href="/lib/bootstrap/css/bootstrap-base-site~/css/jquery.loadmask~z.icons~z.growl~z.modal~z.icons~site~1291008391.css" type="text/css" media="all" rel="stylesheet">
```

Both use absolute urls `"/lib/bootstrap/css/...`. Both should work or be equally broken.

When I look at the browser resources, in the situation of a separate lib, I see this:

![bootstrap-css-resources](https://cloud.githubusercontent.com/assets/350303/7169365/0c9299f6-e3c5-11e4-8228-bcd407490e7b.png)

Apparently something (a folder!) is added to the CSS file. I haven't see this before, but could it be due to the gzip compression?

I also see that bootstrap.min.map is loaded, a hefty 494 KB. This can be prevented by:

1. removing the last line `/*# sourceMappingURL=bootstrap.css.map */` from bootstrap.css
2. using "bootstrap/css/bootstrap.min.css"

I will now look into the update shell script. It's there and pretty straightforward.

**Comment by ArthurClemens** [comment]
* Updated the update script. This will now automatically replace the relative paths to absolute ones.
* `/*# sourceMappingURL` is replaced with `/* sourceMappingURL` so that it is not used to link the sourcemap
* `mod_bootstrap` is updated to v3.3.4 and includes the changes above

**Comment by mworrell** [comment]
:+1:  Thanks!

**Comment by DorienD** [comment]
\o/

**Comment by mmzeeman** [comment]
:trophy:

**Comment by mmzeeman** [comment]
This issue is back again.
