### ISSUE TITLE
Youtube video id in medium

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#941]
Hi!

For a site we want the youtube video in a lightbox (fancybox), but do that we need to make a different url than the url we get from the medium. We need a embed url. The title, provider url and more are provided in the medium but not the video id or the embed url. Could that be added?

~ Dorien

**Comment by mworrell** [comment]
You can't use the embed html?

From oembed (and friends) we receive HTML. Of course it is possible to add specific code to fetch the iframe src url from that HTML, but that might be fragile as it depends on the externally supplied (and sanitized by us) HTML fragment.

**Comment by Devenwel** [comment]
We can't use the embed HTML since we want to feed it to the lightbox component. We also can't use the oembed_url (for example: https://youtu.be/e5oOAO4j3MQ) since that generates a cross-site loading error. The only thing that works is generating a URL like this: http://www.youtube.com/embed/e5oOAO4j3MQ, but it would be nice to have easy access to the video ID.

**Comment by arjan** [comment]
The OEmbed module gets a snippet of JSON from YouTube and stores it.

Example:
http://www.youtube.com/oembed?url=http%3A//www.youtube.com/watch?v%3D-UUx10KOWIE&format=json

The thing is that there is no Id field in this JSON object. This means that we would need to extract it from the URL, which is not very straightforward because Youtube URLs have multiple appearances.

I would suggest creating a filter called `extract_youtube_id` which you would apply to the `oembed_url` property of the resource:

    {{ id.medium.oembed_url|extract_youtube_id }}

**Comment by mworrell** [comment]
Shouldn't this be more generic?
It depends on the modules how the Youtube video is embedded.

For one, there is a "shortcut" now to circumvent the oembed call for "known" urls, so we can handle Youtube et al directly. 

So you can have:

 * OEmbed
 * User supplied HTML snippet
 * HTML generated by mod_video_embed (currently Youtube and Vimeo)

Best is then to use some extra logic on the resource id to fetch the Youtube id.
And what about Vimeo?

**Comment by mworrell** [comment]
BTW, the `src` attribute of the generated HTML `<iframe/>` might always be the url you want to use.
So in that case it is better to have a filter like `extract_embed_src` ?

**Comment by arjan** [comment]
ping @DorienD

**Comment by DorienD** [comment]
From vimeo we get the video ID, we don't from Youtube. And if you want to add a new media item and say embed url then you have to give the watch url from Youtube. So i'm not sure how you could make a extract_embed_src filter if the link you give zotonic is the watch url.

**Comment by mworrell** [comment]
@DorienD we have specialized modules for content providers, they will be able to extract the needed ids.

**Comment by mworrell** [comment]
Actually, they already do so, see for example the following lines:

https://github.com/zotonic/zotonic/blob/master/modules/mod_video_embed/mod_video_embed.erl#L211

https://github.com/zotonic/zotonic/blob/master/modules/mod_video_embed/mod_video_embed.erl#L322

https://github.com/zotonic/zotonic/blob/master/modules/mod_video_embed/mod_video_embed.erl#L339

**Comment by mworrell** [comment]
Maybe add a filter `medium_service_content_id` ?  It would take either a medium record or resource id as the input, and return a binary with the id or `undefined`. The service itself is already a property (_youtube_, _yandex_, etc.)
