### ISSUE TITLE
[RFC] Properties on edges

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#944]
Sometimes it makes sense to put properties on edges and not only on resources. For instance, if you have a dated relationship like `person LIVED_IN city`, you may want to specify a begin and end date of the period that the person lived in that city on the `LIVED_IN` relation. The only way to map this relation without edge properties would be to introduce an extra resource, something like: `person HAD stay` with date properties on `stay` and an additional `stay LOCATED_IN city`.

Advantages to having properties on edges:
* makes for a more straightforward data model
* easier templating?

Disadvantages:
* the conversion from Zotonic data to internet standard RDF (when publishing linked data) becomes harder, as RDF has no properties on links either

Some questions:

1. Anymeta, Zotonic’s predecessor, did have edge properties. What were the reasons for not adopting them in Zotonic? 
2. How would edge properties influence Zotonic performance?
3. What kind of UI would we need to manage edge properties in a user-friendly manner?
4. Did I fail to mention any pros or cons?

**Comment by mworrell** [comment]
Answers:

1. We did not add them due to: complexity, difficult RDF mapping, performance issues. And that a full blown extra resource ('stay' in your example) is actually often a better solution. The properties made the edges into a kind of "light thing".

2. Edge properties would be slower if they are stored in the edge table (sometimes table scans are needed).  You could think of a separate table where you could add properties. This will add extra complexity, joins, caching issues, etc.

3. The UI (and UX) would be complex, as those edge properties tend to come with a feature creep. You need translations, date ranges etc.

4. I don't see the problem of having separate resources representing something like a `stay`. Because it might be: multiple people, a date range, a description, a photo etc.  Any performance problems for following edges can be solved by adding pivot tables. I actually fail to see the advantages.

**Comment by ddeboer** [comment]
Thanks, Marc, that reflects my feelings about edge properties. Let’s see what @fredpook, @arjan and others think.

**Comment by arjan** [comment]
I have only felt the need for edge properties once, and then I ended up storing them in `m_tkvstore`, which worked pretty well.

**Comment by fredpook** [comment]
The only edge property in Anymeta that makes sense to me is a date range.
If we could have just a start and end datein the edge table in Zotonic it would avoid "unnatural" extra resources to model temporal data.

**Comment by mworrell** [comment]
I think we could make it in the admin easier to make (and edit) these "connecting" resources. Then they would be a lot easier to use and maintain.  Especially now with the 'is_dependent' flag it is easier to keep track of this kind of resources.

It would also be nice to make *referring* resources in the admin (as in: this person is the author of that new book).

I think when this is done then we make everything smoother, without adding complexity to the data models (and query models).
