### ISSUE TITLE
mod_admin: rsc title should be required

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#949]
Maybe this is intentional but if so please give an example of a working validation so we can overwrite the template in our projects.

**Comment by mworrell** [comment]
This is intentional.

One of the reasons is that some content comes without a title. Another is that some hidden translation might nog have a title, which is quite a challenge to correctly flag in the UI.

In the resource-add-dialog the title is required though, so there won't be too many resources created without a title.

If you do need to add a client-side validation, then you can add do so by adding a validation for all input elements with the class `field-title`, check the `z_add_validator(id, type, args)` to see how to add the validation.

**Comment by arjan** [comment]
If it's a wontfix, I guess we can close it?

**Comment by mworrell** [comment]
Indeed - I gave a slight 'grace' period for any additional comments.
