### ISSUE TITLE
Make redirection configurable

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#994]
Add an option to redirect to the `website` property of a resource.
This should be handled by controller_page.

/cc @arjan @fredpook 

This is a mapping of the `redirect_uri` property of Anymeta.
(removing any language dependent variations of Anymeta)

**Comment by mworrell** [comment]
Discussion: also add such an option for the optional redirection to the page_path?  (see controller option `is_canonical`)

**Comment by fredpook** [comment]
Adding an option for redirecting to the website property is nice to have for resources that have an address like organizations. Many rsc don't have the address admin block so those can't use this for redirecting. 
The option for redirecting to the page_path is a must-have for ex anymeta sites since redirecting is used (or abused) for all kinds of internal redirecting.

**Comment by mworrell** [comment]
Fixed in aba6f0d54731d85a606f9bd03c9e557a6dc97458
