### ISSUE TITLE
mod_search: crashes on unknown predicate

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#998]
backtrace:

{error,{error,{badmatch,{error,{unknown_predicate,"interest"}}},[{m_predicate,name_to_id_check,2,[{file,"src/models/m_predicate.erl"},{line,129}]},{search_query,parse_query,3,[{file,"modules/mod_search/support/search_query.erl"},{line,218}]},{search_query,search,2,[{file,"modules/mod_search/support/search_query.erl"},{line,48}]},{z_notifier,first1,3,[{file,"src/support/z_notifier.erl"},{line,189}]},{z_search,search,3,[{file,"src/support/z_search.erl"},{line,101}]},{m_search,search,2,[{file,"src/models/m_search.erl"},{line,81}]},{m_search,m_find_value,3,[{file,"src/models/m_search.erl"},{line,56}]},{template_hart_amsterdammuseum__desktop_vagrant_modules_mod_am_default_templates_page_person_tpl,render2,2,[]}]}}

**Comment by mworrell** [comment]
I think that in this case we should return either the empty set or ignore the predicate question.

/cc @arjan

**Comment by arjan** [comment]
I am not sure.

A query with a wrong predicate could be considered a programming error, which is why it crashes like this. Queries are supposed to be written by programmers or people who know what they are doing.  Silently ignoring errors like this results in unexpected behaviour, people not understanding why their query not works like it should, etc.

**Comment by mworrell** [comment]
The queries are also coming from the 'query' collection, which is maintained/edited by editors.
Maybe:

 * Log an error
 * Try to add a growl error to the page (if page id is known)
 * Execute the query with a non-existing id substituted (this will result in an empty result set)

This will make editing a query less error-prone, as there is clear feedback about errors (instead of a crash resulting in a "white screen")
